version: '3.8'
services:
  app:
    image: ${IMAGE_WITH_TAG}
    restart: always
    ports:
      -  8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: shorya
      MYSQL_PASSWORD: Shorya@_1104
      MYSQL_PORT: 3306
  mysqldb:
    image: mysql:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Shorya1104   # Change this to your desired root password
      MYSQL_DATABASE: urotaxidb       # Change this to your desired database name
      MYSQL_USER: shorya               # Change this to your desired username
      MYSQL_PASSWORD: Shorya@_1104      # Change this to your desired password for the user
    ports:
      - "3306:3306"   # Expose MySQL port to host machine
    volumes:
      - mysql_data:/var/lib/mysql           # Persist data to host machine
      # - ./mysql-scripts:/docker-entrypoint-initdb.d   # Optional: Load SQL scripts on container startup
  
volumes:
  mysql_data:
