version: '3.8'
services:
  app:
    image: ${IMAGE_WITH_TAG}
    restart: always
    ports:
      -  8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Shorya@_1104
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.28
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROT_PASSWORD: Shorya@_1104
      - MYSQL_DATABASE: urotaxi
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: