version: '3.8'
services:
  app:
    image: ${IMAGE_NAME}
    restart: always
    ports:
      -  8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.28
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER: "admin"
      - MYSQL_ROT_PASSWORD: ${MYSQL_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: