server:
  port: 8082
spring:
  application:
    name: urotaxi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/urotaxidb
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mvc:
    view:
      suffix: .html
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health